version: '3.8'
services:
  kulps-website:
    build: .
    container_name: kulps-website
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro